### PR TITLE
Share token storage

### LINKED ISSUE #29: Share token URL rewrite causes tab titles to be rewritten to the URL in (at least) firefox
After URL rewrite (to add *e.g.* `?AT=123456`), the page title in a browser tab gets rewritten to be the new URL.

### LINKED ISSUE #43: History.replaceState(null, null, '?foo=bar'); does not work within an iFrame

### LINKED ISSUE #58: If using fallback cookies, session storage and persistent storage will overwrite one another
`STORE_NAME` is used for all types of storage at present. This is fine in the case of localStorage/sessionStorage as they are two different stores, but where storage falls back to using cookies, the session storage cookies will overwrite the persistent cookies.

We should also look at setting an expiry for the session cookies.

### PR DESCRIPTION
**Pull request by nbrl**
On `createToken` we now store the array of token data `[ { token: ...} ... ]` in session storage in addition to `AT.shareTokens`. This allows the possible scenario of:

* navigate to page A and create a token
* navigate to page B (*e.g.* logged in) and we want update that token without referring to it. Not a behaviour we should keep, but useful for now. This should be addresses by `updateAllTokens` when it is written.

`createToken`, `updateToken`, `consumeToken` and `registerTouch` will now fallback to using `window.advocate_things_data` if `data` is `undefined`.

On a side note, fixes #29.
Now fixes #58.

### CODE REVIEW

File: src/sdk.js [hunk 1]
```diff
@@ -384,6 +402,54 @@
         }
     };
 
+    // Always store under apiKey
+    AT._storeShareTokens = function (data) {
+        AT._log('info', '_storeShareTokens()');
+        if (!data || Object.prototype.toString.call(data) !== '[object Array]' || !data[0].token) {
```
Comment (jabclab) [inline src/sdk.js]: Is there a reason we only check the first `Object` within `data` for the `token` property?

File: src/sdk.js [hunk 2]
```diff
@@ -546,6 +614,7 @@
             var tokens = JSON.parse(xhr.responseText);
 
             AT.shareTokens = tokens; // Make everything available
+            AT._storeShareTokens(tokens);
```
Comment (jabclab) [inline src/sdk.js]: reckon it's worth using `Array.prototype.map` like functionality to only store the tokens? Or do you need to have the additional metadata too (query param name etc.)?

Comment (nbrl) [inline src/sdk.js]: Up to you - I'm storing everything for the time being in case it is useful, but if you think we'd be better off just storing the tokens, then I'll make the change.

File: src/sdk.js (hunk 1 above)
Comment (nbrl) [inline src/sdk.js]: Yeah, not sure why that was now - it might have been a primitive test for the "right type" of object. Considering your comment below, we might be best off just storing the tokens, negating this comment.

Comment (nbrl) [inline src/sdk.js]: ...and good news! `Array.prototype.map` made its first appearance in *** drumroll *** IE9!

Comment (jabclab) [inline src/sdk.js]: Haha got to love IE :sob:

File: src/sdk.js [hunk 3]
```diff
@@ -460,7 +546,7 @@
 
         xhr.onload = function () {
             // Handle error responses.
-            if (!/^20[0-9]{1}/.test(xhr.status)) {
+            if (!/^200$/.test(xhr.status)) {
```
Comment (jabclab) [inline src/sdk.js]: Still need a regex for this one?

Comment (nbrl) [inline src/sdk.js]: That is a fair point... All of them could do with changing - good spot

**Comment by jabclab** [comment]
Reckon it might be worth creating a new file in `lib/` for type checking functions? e.g.

```js
// lib/typeChecks.js
this.isObject = function (x) {
  return Object.prototype.toString.call(x) === '[object Object]';
};

this.isFunction = function (x) {
  return typeof x === 'function';
};
```

And then could use like:

```js
if (AT._utils.isObject(x)) {
  // it's an object...
}
```

File: lib/sessionStorage.js [hunk 4]
```diff
@@ -0,0 +1,19 @@
+/**
+ * Simple interface for localStorage to match cookies.
```
Comment (jabclab) [inline lib/sessionStorage.js]: `s/local/session/`

File: src/sdk.js [hunk 5]
```diff
@@ -384,6 +403,54 @@
...
+            // return;
+            sessionStore.setItem(STORAGE_NAME, JSON.stringify({}), Infinity);
+        }
+
+        // Retrieve what is currently in storage
+        var current = JSON.parse(store.getItem(STORAGE_NAME));
+
+        var apiKey = config.apiKey;
+
+        current[apiKey] = data;
```
Comment (jabclab) [inline src/sdk.js]: Do we want to just override what is already there or do we want to use something like [`Array.prototype.concat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat) to maintain existing data?

File: src/sdk.js [hunk 6]
```diff
@@ -473,7 +559,7 @@
 
             AT._storeTouchpointData(res);
 
-            var meta = res.metadata;
+            var meta = JSON.parse(res.metadata);
```
Comment (jabclab) [inline src/sdk.js]: Still want this fix in or reckon it's worth seeing how much work is required in the TDC?

File: src/sdk.js [hunk 7]
```diff
@@ -568,13 +655,50 @@
...
+            if (cb) {
+                return cb(new Error('[updateToken] You must specify data to update with.'));
+            }
+
+            return;
+        }
+
+        if (!token) {
+            // If no token defined, assume we want the first.
+            token = AT._getShareTokens()[0];
```
Comment (jabclab) [inline src/sdk.js]: As `AT._getShareTokens()[0]` is used a few times to denote getting the default token to act on do you think it might be worth wrapping in another private function, e.g. `AT._getDefaultToken`?

**Comment by jabclab** [comment]
Not a blocker to merge but do you think it would be worth having a private constant, e.g. `GLOBAL_DATA`, variable which contains the variable name of our global data object, i.e. `advocate_things_data`?

e.g.
```
AT._prepareData(data || window[GLOBAL_DATA])
```

File: src/sdk.js (hunk 2 above)
Comment (jabclab) [inline src/sdk.js]: I guess it's possible to imagine wanting the query param name (and whether `abs` is on) so as to facilitate rebuilding of share URL. However, I think that because at this stage we only need tokens let's go for only storing tokens. Also it would lead to greater efficiency as we wouldn't have to iterate through and `.push()` tokens during `AT._getShareTokens`. Happy with that?

File: src/sdk.js [hunk 8]
```diff
@@ -522,9 +608,9 @@
             data = null;
         }
 
-        var token;
+        var token; // TODO: is this used?
```
Comment (jabclab) [inline src/sdk.js]: Probably worth checking now and removing if not being used.

File: src/sdk.js [hunk 9]
```diff
@@ -357,6 +375,7 @@
             return;
         }
 
+        // TODO: this should be in init storage
```
Comment (jabclab) [inline src/sdk.js]: Would be nice to do this now if it's not too much hassle.

File: src/sdk.js [hunk 10]
```diff
@@ -384,6 +403,54 @@
...
+
+        var apiKey = config.apiKey;
+
+        current[apiKey] = data;
+
+        sessionStore.setItem(STORAGE_NAME, JSON.stringify(current), Infinity);
+    };
+
+    AT._getShareTokens = function () {
+        if (!sessionStore.hasItem(STORAGE_NAME)) {
```
Comment (jabclab) [inline src/sdk.js]: Can be removed if we ensure the property exists in `AT._initSessionStorage`.

File: src/sdk.js (hunk 5 above)
Comment (nbrl) [inline src/sdk.js]: I went with the overwrite as every time this is called we'll get an array of valid share tokens for each Sharepoint on the page. If we appended, we'd potentially end up with an array of share tokens, some of which had been consumed, some of which had not. If we're appending, it should probably be keyed by Sharepoint or similar?

File: src/sdk.js (hunk 2 above)
Comment (nbrl) [inline src/sdk.js]: Yep, now fixed.

File: lib/sessionStorage.js (hunk 4 above)
Comment (nbrl) [inline lib/sessionStorage.js]: Fixed.

Also opened an issue for the above (type assertion).

File: src/sdk.js (hunk 6 above)
Comment (nbrl) [inline src/sdk.js]: TDC fix in place, ready to merge.

File: src/sdk.js (hunk 7 above)
Comment (nbrl) [inline src/sdk.js]: Good plan, will do.

Comment (nbrl) [inline src/sdk.js]: Done

File: src/sdk.js (hunk 8 above)
Comment (nbrl) [inline src/sdk.js]: Good spot - missed it.

File: src/sdk.js (hunk 9 above)
Comment (nbrl) [inline src/sdk.js]: Yep done for all occurences.

File: src/sdk.js (hunk 10 above)
Comment (nbrl) [inline src/sdk.js]: Done

**Comment by nbrl** [comment]
Re: `window[GLOBAL_DATA]` do you envisage `GLOBAL_DATA` as an internal var, or an external under `AT.GLOBAL_DATA`?

**Comment by jabclab** [comment]
The following is possible I guess:

```js
window.atAsyncInit = function () {
  window[AT.GLOBAL_DATA] = {
    _at: { user_id: '{{ user_id }}', name: '{{ first_name }} {{ last_name }}' }
  };

  AT.init({
    apiKey: 'my_key'
  });
};

(function (d, s, id){
  // ...
}(document, 'script', 'advocate-things-jssdk'));
```

However I would suspect people would like to know what variables are going into the global scope so they know their existing variables won't be clobbered. Admittedly you could just `console.log(AT.GLOBAL_DATA)` but I think I would prefer it to be explicit.

Therefore I would go for private :smile:

File: src/sdk.js [hunk 11]
```diff
@@ -271,13 +273,44 @@
...
+        // Initialise if needed
+        if (!store.hasItem(STORAGE_NAME)) {
+            store.setItem(STORAGE_NAME, JSON.stringify({}), Infinity);
+        }
+
+        return store;
+    };
+
+    /**
+     *
```
Comment (jabclab) [inline src/sdk.js]: Empty JSDoc.

File: src/sdk.js [hunk 12]
```diff
@@ -271,13 +273,44 @@
...
+
+                store = AT._utils.sesStorage;
+            } catch (e) {
+                AT._log('warn', 'Failed to initialise sessionStorage, falling back to cookies');
+            }
+        }
+
+        // Initialise if needed
+        if (!store.hasItem(SESSION_STORAGE_NAME)) {
+            store.setItem(STORAGE_NAME, JSON.stringify({}), Infinity);
```
Comment (jabclab) [inline src/sdk.js]: `s/STORAGE_NAME/SESSION_STORAGE_NAME/`

Comment (jabclab) [inline src/sdk.js]: A minor one, I guess it would be more efficient just to use `'{}'` for the second arg.

File: src/sdk.js [hunk 13]
```diff
@@ -385,6 +414,48 @@
     };
 
     /**
+     *
```
Comment (jabclab) [inline src/sdk.js]: Empty JSDoc.

File: src/sdk.js (hunk 11 above)
Comment (nbrl) [inline src/sdk.js]: ?

File: src/sdk.js [hunk 14]
```diff
@@ -385,6 +417,48 @@
...
+     */
+    AT._storeShareTokens = function (data) {
+        AT._log('info', '_storeShareTokens()');
+        if (!data || Object.prototype.toString.call(data) !== '[object Array]') {
+            return;
+        }
+
+        // Retrieve what is currently in storage
+        var current = JSON.parse(sessionStore.getItem(STORAGE_NAME));
```
Comment (jabclab) [inline src/sdk.js]: `s/STORAGE_NAME/SESSION_STORAGE_NAME/`

File: src/sdk.js [hunk 15]
```diff
@@ -385,6 +417,48 @@
...
+        for (var i=0, len=data.length; i<len; i++) {
+            if (Object.prototype.toString.call(data[i]) === '[object Object]' &&
+                data[i].hasOwnProperty('token')) {
+                tokens.push(data[i].token);
+            }
+        }
+
+        current[apiKey] = tokens;
+
+        sessionStore.setItem(STORAGE_NAME, JSON.stringify(current), Infinity);
```
Comment (jabclab) [inline src/sdk.js]: `s/STORAGE_NAME/SESSION_STORAGE_NAME/`

File: src/sdk.js [hunk 16]
```diff
@@ -385,6 +417,48 @@
...
+    };
+
+    /**
+     *
+     */
+    AT._getShareTokens = function () {
+        var storeData = JSON.parse(sessionStore.getItem(STORAGE_NAME));
```
Comment (jabclab) [inline src/sdk.js]: `s/STORAGE_NAME/SESSION_STORAGE_NAME/`

File: src/sdk.js [hunk 17]
```diff
@@ -385,6 +417,48 @@
...
+            }
+        }
+
+        current[apiKey] = tokens;
+
+        sessionStore.setItem(STORAGE_NAME, JSON.stringify(current), Infinity);
+    };
+
+    /**
+     *
```
Comment (jabclab) [inline src/sdk.js]: Empty JSDoc.

File: src/sdk.js [hunk 18]
```diff
@@ -385,6 +417,48 @@
...
+    AT._getShareTokens = function () {
+        var storeData = JSON.parse(sessionStore.getItem(STORAGE_NAME));
+
+        var apiKey = config.apiKey;
+
+        if (!storeData[apiKey]) {
+            return [];
+        }
+
+        return storeData[apiKey];
```
Comment (jabclab) [inline src/sdk.js]: How about:

```js
return storeData[apiKey] || [];
```

File: src/sdk.js [hunk 19]
```diff
@@ -445,13 +520,31 @@
     requireKey.registerTouch = function (name, data, cb) {
         AT._log('info', 'registerTouch()');
 
-        var dataPrep = AT._prepareData(data);
+        // Let's work out what's what
+        if (Object.prototype.toString.call(name) === '[object Object]') {
```
Comment (jabclab) [inline src/sdk.js]: Do we need to cater for IE and `null`/`undefined`?

File: src/sdk.js (hunk 18 above)
Comment (nbrl) [inline src/sdk.js]: Yep that would be better - the below will go red if it doesn't, but I don't see why it wouldn't.

File: src/sdk.js [hunk 20]
```diff
@@ -445,13 +520,31 @@
...
+            name = null;
+        }
+
+        if (typeof name === 'function') {
+            cb = name;
+            name = null;
+            data = null;
+        }
+
+        if (typeof data === 'function') {
```
Comment (jabclab) [inline src/sdk.js]: What about `name` in this scenario? Are we going to do with if it's of the wrong type (e.g. `Array`) the method will just fall over?

File: src/sdk.js [hunk 21]
```diff
@@ -505,7 +598,7 @@
         AT._log('info', 'createToken()');
 
         // Let's work out what's what
-        if (typeof name === 'object') {
+        if (Object.prototype.toString.call(name) === '[object Object]' && name !== null) {
```
Comment (jabclab) [inline src/sdk.js]: Do we also want to check for `undefined` here?

File: src/sdk.js [hunk 22]
```diff
@@ -568,13 +660,50 @@
...
+     *                           updated. Defaults to the first token in session
+     *                           storage.
      * @param {object} data - The data to augment previous data with.
      * @param {function} [cb] - Callback function with (err, token).
      */
     requireKey.updateToken = function (token, data, cb) {
         AT._log('info', 'updateToken()');
+
+        // Let's work out what's what
+        if (Object.prototype.toString.call(token) === '[object Object]' && token !== null) {
```
Comment (jabclab) [inline src/sdk.js]: Check for `undefined` needed too?

File: src/sdk.js [hunk 23]
```diff
@@ -568,13 +660,50 @@
...
+
+        if (typeof token === 'function') {
+            cb = token;
+            token = null;
+            data = null;
+        }
+
+        if (typeof data === 'function') {
+            cb = data;
+            data = null;
```
Comment (jabclab) [inline src/sdk.js]: Do we want to do anything with `token` here or allow to fail if not a `String`?

File: src/sdk.js [hunk 24]
```diff
@@ -568,13 +660,50 @@
...
+        }
+
+        if (!data) {
```
Comment (jabclab) [inline src/sdk.js]: Seeing `if (!data) {` twice in close succession is a little confusing. How about giving `data` a "default" value of `window[GLOBAL_DATA]` above (in the arg normalisation)?

File: src/sdk.js [hunk 25]
```diff
@@ -568,13 +660,50 @@
...
+            data = window[GLOBAL_DATA];
+        }
+
+        if (!data) {
```
Comment (jabclab) [inline src/sdk.js]: May be worth adding a comment here as when I first saw `if (!data) {` it was a little confusing.

File: src/sdk.js [hunk 26]
```diff
@@ -622,6 +751,18 @@
...
+            cb = token;
+            token = null;
+        }
+
+        if (!token) {
+            // If no token defined, grab the default
+            token = AT.getDefaultToken();
+        }
+
         if (!token) {
```
Comment (jabclab) [inline src/sdk.js]: May be worth adding a comment here as when I first saw `if (!token) {` twice it was a little confusing.

File: src/sdk.js [hunk 27]
```diff
@@ -670,6 +811,30 @@
      * @param {function} [cb] - Callback function with (err, tokens).
      */
     requireKey.consumeToken = function (token, data, cb) {
+        // Let's work out what's what
+
+        if (Object.prototype.toString.call(token) === '[object Object]' && token !== null) {
```
Comment (jabclab) [inline src/sdk.js]: Need to cater for `undefined` here?

File: src/sdk.js [hunk 28]
```diff
@@ -670,6 +811,30 @@
...
+        }
+
+        if (typeof token === 'function') {
+            cb = token;
+            token = null;
+            data = null;
+        }
+
+        if (typeof data === 'function') {
+            cb = data;
```
Comment (jabclab) [inline src/sdk.js]: Need to do anything with `token` here?

File: src/sdk.js [hunk 29]
```diff
@@ -670,6 +811,30 @@
...
+            data = null;
+        }
+
+        if (!token) {
+            // If no token defined, grab the default.
+            token = AT.getDefaultToken();
+        }
+
         if (!token) {
```
Comment (jabclab) [inline src/sdk.js]: May be worth adding a comment here as when I first saw `if (!token) {` twice it was a little confusing.

File: src/sdk.js [hunk 30]
```diff
@@ -719,18 +884,22 @@
         }
     };
 
+    AT.getDefaultToken = function () {
```
Comment (jabclab) [inline src/sdk.js]: JSDoc missing.

File: src/sdk.js [hunk 31]
```diff
@@ -719,18 +884,22 @@
...
+        return AT._getShareTokens()[0] || null;
+    };
+
     /**
      * Initialisation function
      */
 
     /**
-     * Automatically sends window.advocate_things_data as a touchpoint or
```
Comment (jabclab) [inline src/sdk.js]: Not introduced by this PR but the JSDoc suggests a callback is passable yet it doesn't seem to be included in the function signature/obtained using `arguments`. Do you want to handle here or create a separate issue?

File: src/sdk.js [hunk 32]
```diff
@@ -385,6 +418,45 @@
...
+        }
+
+        // Retrieve what is currently in storage
+        var current = JSON.parse(sessionStore.getItem(SESSION_STORAGE_NAME));
+
+        var apiKey = config.apiKey;
+
+        var tokens = [];
+        for (var i=0, len=data.length; i<len; i++) {
+            if (Object.prototype.toString.call(data[i]) === '[object Object]' &&
```
Comment (jabclab) [inline src/sdk.js]: Our favourite IE gotcha

**Comment by jabclab** [comment]
Need to convey the fact that all args are optional for `xToken()` methods in the JSDoc.
