### PR TITLE
Break out functions

### LINKED ISSUE #46: Consider use of API key checking
Namely, in `AT.addEventListener` but is throughout the SDK. At present, `AT.addEventListener` will return null if there is no API key. If there is an API key, nothing is returned and so a *successful* return is `undefined`. If we didn't explicitly `return null` it wouldn't be possible to test which branch of code we have traversed as the return will always be `undefined`.

Opening this as a discussion for how to proceed. Commonly, it seems that the approach is, "let it fail," and simply allowing event listeners to be added, accepting that they have no way to be called.

As well as this function, the API key test is in numerous other functions. Perhaps we should consider some sort of equivalent to *e.g.* express running authenticated routes through an `isAuthenticated` type function.

### PR DESCRIPTION
**Pull request by nbrl**
`sendSharepoint` and `sendTouchpoint` hid a lot of *magic* functionality depending on what parameters the called data object had. This functionality has been split out into 5 new functions which although is a little more manual for now make it much more obvious what is happening/will happen. The new functions are:

* `createToken` - creates a token / some tokens
* `updateToken` - updates the metadata associated with the given token
* `lockToken` - locks the given token to prevent further updates
* `consumeToken` - consumes the given token, locking it and specifying that a share has occurred.

We also have a new `gulp` task `build-local` which does as it suggests - builds the SDK as `build` would, but using local IPs. Presently it is hardcoded to `localhost:3000` / `localhost:4000`, but if we decide on some environment variables, we can use those instead.

The testing is incomplete and the documentation has not yet been updated, giving us a chance to test it to make sure if it is what we want before time is spent testing for incorrect functionality or writing irrelevent documentation.

Fixes #46

### CODE REVIEW

**Comment by nbrl** [comment]
FTR the failures above are because I didn't push the deletion of the old test files, which naturally weren't applicable anymore :dromedary_camel:

File: src/sdk.js [hunk 1]
```diff
@@ -24,10 +27,50 @@
...
+        }
+    };
+
     AT.Events = {
-        SharepointSaved: 'SharepointSaved',
-        TouchpointSaved: 'TouchpointSaved',
-        ReferredPerson: 'ReferredPerson'
+        SharepointSaved: 'SharepointSaved', // retire
+        TouchpointSaved: 'TouchpointSaved', // retire
+        ReferredPerson: 'ReferredPerson',   // retire
```
Comment (nbrl) [inline src/sdk.js]: Don't retire.

File: src/sdk.js [hunk 2]
```diff
@@ -318,7 +366,8 @@
         }
 
         var currentlyStoredData = JSON.parse(store.getItem(STORAGE_NAME)); // TODO: try/catch
-        var apiKey = AT._getApiKey();
+        //var apiKey = AT._getApiKey();
```
Comment (nbrl) [inline src/sdk.js]: delete

File: src/sdk.js [hunk 3]
```diff
@@ -479,38 +591,154 @@
             }
         };
 
-        xhr.open('POST', POINTS.Sharepoint.url, isAsync);
+        var call = endpoints.RegisterTouch;
+        xhr.open('POST', call.url, call.async);
```
Comment (nbrl) [inline src/sdk.js]: call.method

File: src/sdk.js [hunk 4]
```diff
@@ -519,31 +747,81 @@
...
+        var call = endpoints.ConsumeToken;
+        xhr.open(call.method, call.url(token), call.async);
         xhr.setRequestHeader('Content-Type', 'application/json; charset=utf-8');
         xhr.send(dataString);
     };
 
+    // Convenience method
+    AT.getAddressBarShareToken = function () {
+        var tokens = AT.shareTokens;
+        for (var t in tokens) {
```
Comment (nbrl) [inline src/sdk.js]: i

File: src/sdk.js [hunk 5]
```diff
@@ -553,30 +831,101 @@
...
+        AT._log('info', '_autoSend()');
         var data = window.advocate_things_data;
 
-        AT.send(data, true, cb);
+        if (config.autoSend === 'touch') {
+            return AT.registerTouch(null, data, cb);
+        }
+
+        // Move to createToken and call from there?
+        if (config.autoLock) {
```
Comment (nbrl) [inline src/sdk.js]: consider

File: src/sdk.js [hunk 6]
```diff
@@ -553,30 +831,101 @@
...
+     * than directly to `AT`. On load, all `requireKey` functions will have their
+     * wrapped equivalents added to `AT`.
      */
-    AT._init = function (cb) {
-        if (!AT._getApiKey()) {
-            return null;
+    function verifyWrap(fn) {
+        return function () {
+            if (!config) {
+                return console.warn('.init() not called');
```
Comment (nbrl) [inline src/sdk.js]: AT._log

File: src/sdk.js [hunk 7]
```diff
@@ -553,30 +831,101 @@
...
+        config = c;
+
+        AT._log('info', 'init()');
+
+        if (!config.apiKey) {
+            AT._log('error', 'No API key specified');
+            return;
+        }
+
+        if (config.autoSend === 'undefined') {
```
Comment (nbrl) [inline src/sdk.js]: no quotes :/

File: gulpfile.js [hunk 8]
```diff
@@ -47,6 +48,16 @@ gulp.task('build', function () {
 });
 
 /**
+ * Build JS suitable for local collectors.
+ */
+gulp.task('build-local', ['build'], function () {
+    return gulp.src('./dist/sdk.js')
+        .pipe(replace(/https:\/\/sharepoint-data-collector.herokuapp.com/g, 'http://127.0.0.1:3000'))
```
Comment (jabclab) [inline gulpfile.js]: Using `gulp-replace` is fine but a templating solution may be easier to maintain going forward, [here's one](https://www.npmjs.com/package/gulp-swig) and [another](https://www.npmjs.com/package/gulp-consolidate/) I found via quick a Google.

File: karma.conf.js [hunk 9]
```diff
@@ -106,62 +106,62 @@ module.exports = function(config) {
...
-        platform: 'Windows 8.1',
-        version: '11.0'
-    },
-    sl_ie10_win7: {
-        base: 'SauceLabs',
-        browserName: 'internet explorer',
-        platform: 'Windows 7',
-        version: '10.0'
-    },
+    // sl_chrome43_win7: {
```
Comment (jabclab) [inline karma.conf.js]: Reinstate

File: src/sdk.js [hunk 10]
```diff
@@ -24,10 +27,50 @@
         }
     };
 
+    var endpoints = {
+        CreateToken: {
+            url: 'https://sharepoint-data-collector.herokuapp.com/share-token/',
```
Comment (jabclab) [inline src/sdk.js]: How about having a consistent structure for these enum values? i.e. `function` for `url`. This would make it easier to maintain and open up the possibility of something like:

```js
function callEndpoint(ep, data, cb) {
  var xhr = new XMLHttpRequest();
  // ...
}
```

File: src/sdk.js [hunk 11]
```diff
@@ -24,10 +27,50 @@
...
-        TouchpointSaved: 'TouchpointSaved',
-        ReferredPerson: 'ReferredPerson'
+        SharepointSaved: 'SharepointSaved', // retire
+        TouchpointSaved: 'TouchpointSaved', // retire
+        ReferredPerson: 'ReferredPerson',   // retire
+        TokenCreated: 'TokenCreated',
+        TokenUpdated: 'TokenUpdated',
+        TokenLocked: 'TokenLocked',
+        TokenConsumed: 'TokenConsumed',
+        RegisteredTouch: 'RegisteredTouch',
```
Comment (jabclab) [inline src/sdk.js]: We mentioned it but `TouchRegistered` probably is more consistent with the rest of event names.

File: src/sdk.js [hunk 12]
```diff
@@ -58,9 +101,27 @@
...
+        AT._log('info', '_appendTokenToUrl()');
+
+        if (Object.prototype.toString.call(tokens) !== '[object Array]') {
+            return;
+        }
+
+        // Iterate array until we find an abs token
+        var token;
+        var qpName;
+        for (var t in tokens) {
```
Comment (jabclab) [inline src/sdk.js]: Might want to consider `for (var i = 0; len = tokens.length; i < len; i++) {}` as if I see `for (var x in y) {}`  I automatically think `Object`. Although that could be my problem :laughing:

File: src/sdk.js [hunk 13]
```diff
@@ -58,9 +101,27 @@
      * @param {string} token - The sharepoint token to insert into the URL.
      * @param {string} qpName - The name to use for the query parameter.
      */
-    AT._appendTokenToUrl = function (token, qpName) {
+    // AT._appendTokenToUrl = function (token, qpName) {
```
Comment (jabclab) [inline src/sdk.js]: Comment to remove?

File: src/sdk.js [hunk 14]
```diff
@@ -160,16 +202,17 @@
      * and browser combination in local/cookie storage.
      * @returns {array} - Array of strings of sharepoint tokens from storage.
      */
-    AT._getSharepointTokens = function () {
+    AT._getShareTokens = function () {
         var tokens = [];
```
Comment (jabclab) [inline src/sdk.js]: May as well move this declaration after the `if (!store...` as could be a wasted declaration as currently stands.

File: src/sdk.js [hunk 15]
```diff
@@ -160,16 +202,17 @@
...
 
         if (!store.hasItem(STORAGE_NAME)) {
-            return tokens;
+            return [];
         }
 
         var storeData = JSON.parse(store.getItem(STORAGE_NAME));
 
-        var apiKey = AT._getApiKey();
+        // var apiKey = AT._getApiKey();
```
Comment (jabclab) [inline src/sdk.js]: Comment to remove?

File: src/sdk.js [hunk 16]
```diff
@@ -347,12 +396,23 @@
      *                        reactions to events.
      */
     AT._triggerEvent = function (eventType, data) {
+        AT._log('info', 'EVT: ' + eventType);
         for (var l=0, len=listeners[eventType].length; l<len; l++) {
```
Comment (jabclab) [inline src/sdk.js]: `s/l/i/`?

File: src/sdk.js [hunk 17]
```diff
@@ -389,29 +451,25 @@
...
-        //     if (data._at.sharepointName) {
-        //         return AT.sendSharepoint(null, data, isInit, cb);
-        //     }
-        // }
-
-        return AT.sendTouchpoint(null, data, function () {
-            return AT.sendSharepoint(null, data, isInit, cb);
-        });
-    };
+    // requireKey.send = function (data, isInit, cb) {
```
Comment (jabclab) [inline src/sdk.js]: Comment to remove?

File: src/sdk.js [hunk 18]
```diff
@@ -426,22 +484,78 @@
      *                             XHRs.
      * @param {function} cb - Callback function, called with (err, res).
      */
-    AT.sendSharepoint = function (name, data, isInit, cb) {
-        if (!AT._getApiKey()) {
-            return null;
-        }
+    // requireKey.sendSharepoint = function (name, data, isInit, cb) {
```
Comment (jabclab) [inline src/sdk.js]: Comment to remove?

File: src/sdk.js [hunk 19]
```diff
@@ -479,38 +591,154 @@
...
-            dataPrep._at.touchpointName = name;
+            dataPrep._at.sharepointName = name;
+        }
+
+        var dataString = JSON.stringify(dataPrep);
+
+        var xhr = new XMLHttpRequest();
+
+        xhr.onload = function () {
+            if (!/^20[0-9]{1}/.test(xhr.status)) {
```
Comment (jabclab) [inline src/sdk.js]: Could make more specific, it'll always be a `201` from `createToken`.

File: src/sdk.js [hunk 20]
```diff
@@ -479,38 +591,154 @@
...
         }
 
-        dataPrep._at.shareTokens = AT._getSharepointTokens();
+        var xhr = new XMLHttpRequest();
 
+        var dataPrep = AT._prepareData(data);
         var dataString = JSON.stringify(dataPrep);
 
+        xhr.onload = function () {
+            if (!/^20[0-9]{1}/.test(xhr.status)) {
```
Comment (jabclab) [inline src/sdk.js]: Could make more specific, it'll always be a `200` from `updateToken`.

File: src/sdk.js [hunk 21]
```diff
@@ -479,38 +591,154 @@
...
+
         var xhr = new XMLHttpRequest();
-        var isAsync = true;
+
+        var dataPrep = AT._prepareData(data); // TODO: needed for adding api key to data
+        var dataString = JSON.stringify(dataPrep);
 
         xhr.onload = function () {
-            // Handle error responses.
             if (!/^20[0-9]{1}/.test(xhr.status)) {
```
Comment (jabclab) [inline src/sdk.js]: Could make more specific, it'll always be a `200` from `lockToken`.

File: src/sdk.js [hunk 22]
```diff
@@ -519,31 +747,81 @@
...
+            return;
+        }
+
+        var xhr = new XMLHttpRequest();
+
+        var dataPrep = AT._prepareData(data); // TODO: needed for adding api key to data
+        var dataString = JSON.stringify(dataPrep);
+
+        xhr.onload = function () {
+            if (!/^20[0-9]{1}/.test(xhr.status)) {
```
Comment (jabclab) [inline src/sdk.js]: Could make more specific, it'll always be a `200` from `consumeToken`.

File: src/sdk.js [hunk 23]
```diff
@@ -479,38 +591,154 @@
...
+                return cb(new Error('[lockToken] You must specify a token to lock.'));
+            }
+
+            return;
+        }
+
         var xhr = new XMLHttpRequest();
-        var isAsync = true;
+
+        var dataPrep = AT._prepareData(data); // TODO: needed for adding api key to data
```
Comment (jabclab) [inline src/sdk.js]: This `TODO` still required?

File: src/sdk.js (hunk 5 above)
Comment (jabclab) [inline src/sdk.js]: As part of the consideration may want to think about how multiple token locking is handled, e.g. is the `cb` called after the first one is locked or after all?

File: src/sdk.js [hunk 24]
```diff
@@ -553,30 +831,101 @@
...
-        if (!AT._getApiKey()) {
-            return null;
+    function verifyWrap(fn) {
+        return function () {
+            if (!config) {
+                return console.warn('.init() not called');
+            }
+
+            if (!config.apiKey) {
+                return console.warn('No API key');
```
Comment (jabclab) [inline src/sdk.js]: `AT._log` :pager:

File: src/sdk.js [hunk 25]
```diff
@@ -553,30 +831,101 @@
...
-        AT.send(data, true, cb);
+        if (config.autoSend === 'touch') {
+            return AT.registerTouch(null, data, cb);
+        }
+
+        // Move to createToken and call from there?
+        if (config.autoLock) {
+            cb = function (err, tokens, cb) {
+                // TODO: handle error
+                for (var t in tokens) {
```
Comment (jabclab) [inline src/sdk.js]: `for (var i, len...` ?

File: src/sdk.js (hunk 10 above)
Comment (jabclab) [inline src/sdk.js]: I think this would be a nice way to go if you've got time as there's quite a lot of code repeated for handling XHRs (success, failure, expected response code etc.) :camel:

File: src/sdk.js [hunk 26]
```diff
@@ -519,31 +747,81 @@
...
+            if (cb) {
+                return cb(new Error('[consumeToken] You must specify a token to consume.'));
+            }
+
+            return;
+        }
+
+        var xhr = new XMLHttpRequest();
+
+        var dataPrep = AT._prepareData(data); // TODO: needed for adding api key to data
```
Comment (jabclab) [inline src/sdk.js]: `TODO` still required?

File: src/sdk.js [hunk 27]
```diff
@@ -1,8 +1,11 @@
- ;(function (context) {
+;(function (context) {
     // Variables
-    var AT = {};
+    var AT = {}; // Contains methods that will be exported.
+    var requireKey = {}; // Contains methods that will be exported (under AT), after being wrapped.
+
     var listeners = {};
     var store = null;
+    var config = {};
```
Comment (jabclab) [inline src/sdk.js]: Do you think it might be useful to name these IIFE-private vars `_xxx` so that in the context of functions its obvious they are 'special'?

**Comment by jabclab** [comment]
Just need to make sure the `*.bak` files are deleted :rooster:

File: src/sdk.js (hunk 1 above)
Comment (nbrl) [inline src/sdk.js]: Done.

File: src/sdk.js (hunk 2 above)
Comment (nbrl) [inline src/sdk.js]: Done

File: src/sdk.js (hunk 3 above)
Comment (nbrl) [inline src/sdk.js]: fixed

File: src/sdk.js (hunk 4 above)
Comment (nbrl) [inline src/sdk.js]: leaving for now

File: src/sdk.js (hunk 6 above)
Comment (nbrl) [inline src/sdk.js]: fixed

File: src/sdk.js (hunk 7 above)
Comment (nbrl) [inline src/sdk.js]: fixed...

File: gulpfile.js (hunk 8 above)
Comment (nbrl) [inline gulpfile.js]: To be fixed. See issue #51

File: karma.conf.js (hunk 9 above)
Comment (nbrl) [inline karma.conf.js]: done

File: src/sdk.js (hunk 10 above)
Comment (nbrl) [inline src/sdk.js]: Yep, there is either an issue for this or there should be one. Issue #52

File: src/sdk.js (hunk 11 above)
Comment (nbrl) [inline src/sdk.js]: done

File: src/sdk.js (hunk 12 above)
Comment (nbrl) [inline src/sdk.js]: "fixed"

File: src/sdk.js (hunk 13 above)
Comment (nbrl) [inline src/sdk.js]: yep

File: src/sdk.js (hunk 14 above)
Comment (nbrl) [inline src/sdk.js]: fixed, though this function does not appear to be working - will look at it

File: src/sdk.js (hunk 15 above)
Comment (nbrl) [inline src/sdk.js]: yep

File: src/sdk.js (hunk 16 above)
Comment (nbrl) [inline src/sdk.js]: yep

File: src/sdk.js (hunk 17 above)
Comment (nbrl) [inline src/sdk.js]: yep

File: src/sdk.js (hunk 18 above)
Comment (nbrl) [inline src/sdk.js]: yep

File: src/sdk.js (hunk 19 above)
Comment (nbrl) [inline src/sdk.js]: done

File: src/sdk.js (hunk 20 above)
Comment (nbrl) [inline src/sdk.js]: done

File: src/sdk.js (hunk 21 above)
Comment (nbrl) [inline src/sdk.js]: done

File: src/sdk.js (hunk 22 above)
Comment (nbrl) [inline src/sdk.js]: done

File: src/sdk.js (hunk 23 above)
Comment (nbrl) [inline src/sdk.js]: not really

File: src/sdk.js (hunk 24 above)
Comment (nbrl) [inline src/sdk.js]: no more consoles

File: src/sdk.js (hunk 25 above)
Comment (nbrl) [inline src/sdk.js]: yep

File: src/sdk.js (hunk 26 above)
Comment (nbrl) [inline src/sdk.js]: nope

File: src/sdk.js (hunk 27 above)
Comment (nbrl) [inline src/sdk.js]: Perhaps. Issue #53.
